name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Set up Docker SBOM plugin
        run: curl -sSfL https://raw.githubusercontent.com/docker/sbom-cli-plugin/main/install.sh | sh -s --
            
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Docker build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: sujaypillai/javaapp:multiarc-1.0
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64,linux/riscv64,linux/ppc64le,linux/s390x,linux/386,linux/mips64le,linux/mips64,linux/arm/v7,linux/arm/v6
          
      - name: Docker build with SBOM
        run: docker buildx build --cache-from type=gha --tag sujaypillai/javaapp:multiarc-1.0 -o sbom https://github.com/sujaypillai/multiarcjava.git#49957b0f1adf8ce8fa53a1aa9bfc8988b639d8af
              
      - name: List SBOM
        run: ls sbom
        
      - name: Print SBOM
        run: cat sbom/sbom.txt  
        
      - name: Print SBOM
        run: docker sbom sujaypillai/javaapp:multiarc-1.0

